# Default values for django-cms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gioelkin/django-cms
  pullPolicy: IfNotPresent
  tag: 'v1'
postgis:
  fullnameOverride: 'django-cms-db'
  postgres_user: postgres
  postgres_password: 'pass'
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  externalPort: 3000
  internalPort: 80

env:
  - name: DATABASE_URL
    value: 'postgres://postgres:pass@django-cms-db:5432/postgres'
  - name: DEFAULT_STORAGE_DSN
    value: 'file:///data/media/?url=%2Fmedia%2F'
  - name: DEBUG
    value: 'True'
  - name: DOMAIN_ALIASES
    value: 'localhost, 127.0.0.1'
  - name: SECURE_SSL_REDIRECT
    value: 'False'

storage_size: 2Gi
persistentVolumeClaim:
  name: 'django-cms-pv-claim'
  accessModes:
    - ReadWriteOnce
storageClass:
  createClass: false
  provisioner: ''
  storageClassName: ''
  parameters:
    provisioningMode: ''
    fileSystemId: ''
    directoryPerms: ''
    gidRangeStart: ''
    gidRangeEnd: ''
    basePath: ''
  allowVolumeExpansion: true
  volumeBindingMode: ''
  mountOptions: []
  annotations: {}

ingress:
  enabled: true
  className: ''
  annotations: {}
  hosts:
    - host: localhost
      paths:
        - /

  tls: []

resources:
  requests:
    memory: '2Gi'
    cpu: '1'
  limits:
    memory: '4Gi'
nodeSelector: {}
tolerations: []
affinity: {}
