apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: djangocms-persist-pvc
  labels:
{{ include "djangocms.labels" . | indent 4 }}
spec:
  accessModes:
  {{- range .Values.persistentVolumeClaim.accessModes }}
    - {{ . }}
  {{- end }}
  {{- if .Values.storageClass.storageClassName }}
  storageClassName: {{ .Values.storageClass.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage_size | quote }}