apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-cms.fullname" . }}
  labels:
{{- include "django-cms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      name: main-node
  selector:
    app.kubernetes.io/name: {{ include "django-cms.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
